openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-static-postgresql
components:
  schemas:
    variables:
      required:
      - database
      - password
      - username
      type: object
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.

            Examples:
            ```
            context:
              project:
                name: string
                id: string
              environment:
                name: string
                id: string
              resource:
                name: string
                id: string
            ```
          default: {}
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            hidden: true
            order: 1
        selector:
          title: Selector
          type: object
          description: The selector, a map, which is used for dependencies or collaborations.
          default: {}
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 2
        endpoint_internal:
          title: Endpoint Internal
          type: array
          description: The internal endpoints of the resource.
          default: []
          items:
            type: string
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 3
        endpoint_internal_readonly:
          title: Endpoint Internal Readonly
          type: array
          description: The internal readonly endpoints of the resource.
          default: []
          items:
            type: string
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 4
        database:
          title: Database
          type: string
          description: The name of the PostgreSQL database to access.
          x-walrus-ui:
            group: Basic
            order: 5
        username:
          title: Username
          type: string
          description: The username of the account to access the database.
          x-walrus-ui:
            group: Basic
            order: 6
        password:
          title: Password
          type: string
          description: The password of the account to access the database.
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 7
